version: "3.9"
services:
  postgres:
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=heatmap
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - pgstorage:/var/lib/postgresql/data
    networks:
      - heatmap_net
  flask:
    build:
      context: .
      dockerfile: Dockerfile-flask
    container_name: flask
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=heatmap
      - POSTGRES_TABLE=factory
    image: flask
    ports:
      - 5000:5000
    links:
      - postgres
    volumes:
      - ../src/flask:/src
    networks:
      - heatmap_net
  dash:
    build:
      context: .
      dockerfile: Dockerfile-dash
    container_name: dash
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=heatmap
      - POSTGRES_TABLE=factory
    image: dash
    ports:
      - 8050:8050
    links:
      - postgres
      - flask
    volumes:
      - ../src/dash:/src
    networks:
      - heatmap_net
volumes:
  pgstorage:
    external: true
networks:
  heatmap_net:
    external: true
    driver: bridge

