version: "3.9"
services:
  mongo:
    container_name: mongo
    environment:
      - MONGO_INITDB_DATABASE=heatmap
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=admin
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ../src/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - mgstorage:/data/db
    networks:
      - heatmap_net
  flask:
    build:
      context: .
      dockerfile: Dockerfile-flask
    container_name: flask
    environment:
      - MONGO_INITDB_DATABASE=heatmap
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGO_COLLECTION=$MONGO_COLLECTION
      - HEATMAP_WIDTH=$HEATMAP_WIDTH
      - HEATMAP_HEIGHT=$HEATMAP_HEIGHT
    image: flask
    ports:
      - 5000:5000
    depends_on:
      - mongo
    volumes:
      - ../src/flask:/src
    networks:
      - heatmap_net
  dash:
    build:
      context: .
      dockerfile: Dockerfile-dash
    container_name: dash
    environment:
      - MONGO_INITDB_DATABASE=heatmap
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGO_COLLECTION=$MONGO_COLLECTION
      - HEATMAP_WIDTH=$HEATMAP_WIDTH
      - HEATMAP_HEIGHT=$HEATMAP_HEIGHT
    image: dash
    ports:
      - 8050:8050
    depends_on:
      - flask
    volumes:
      - ../src/dash:/src
    networks:
      - heatmap_net

  heatmap_generator:
    build:
      context: .
      dockerfile: Dockerfile-heatmap-gen
    container_name: heatmap_generator
    command: roslaunch thmho_firos_heatmap_bringup docker_bringup.launch
    environment:
      - "ROS_MASTER_URI=http://192.168.1.235:11311"
      - "ROS_IP=192.168.1.235"
    ports:
      - "11311:11311"
    networks:
      heatmap_net:
          ipv4_address: 192.168.1.235

volumes:
  mgstorage:
    external: true


networks:
  heatmap_net:
    external: true
    # driver: bridge
    # ipam:
    #   driver: default
    #   config:
    #     - subnet: 192.168.1.234/24
    #       gateway: 192.168.1.234
