version: "3.9"
services:
  mongo:
    container_name: mongo
    environment:
      - MONGO_INITDB_DATABASE=heatmap
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=admin
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ../src/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - mongostorage:/data/db
    networks:
      - heatmap_net
  mongocsr:
    container_name: mongocsr
    environment:
      - MONGO_INITDB_DATABASE=heatmap
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=admin
    image: mongo
    command: mongod --port 27018
    ports:
      - 27018:27018
    volumes:
      - ../src/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - mongosparse:/data/db
    networks:
      - heatmap_net
  flask:
    build:
      context: .
      dockerfile: Dockerfile-flask
    container_name: flask
    environment:
      - MONGO_INITDB_DATABASE=heatmap
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGO_COLLECTION=$MONGO_COLLECTION
      - HEATMAP_WIDTH=$HEATMAP_WIDTH
      - HEATMAP_HEIGHT=$HEATMAP_HEIGHT
    image: flask
    ports:
      - 5000:5000
    depends_on:
      - mongo
    volumes:
      - ../src/flask:/src
    networks:
      - heatmap_net
volumes:
  mongostorage:
    external: true
  mongosparse:
    external: true
networks:
  heatmap_net:
    external: true
    driver: bridge

